//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THGL_Managment_System.TESTMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anakuklwnei
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anakuklwnei()
        {
            this.Anakuklwsimo_PELPRO = new HashSet<Anakuklwsimo_PELPRO>();
        }
    
        public string Kwdikos_Anakuklwsis { get; set; }
        public string Kwdikos_Pelati { get; set; }
        public Nullable<System.DateTime> Hmeromhnia { get; set; }
        public Nullable<int> pontoi { get; set; }
    
        public virtual Pelatis Pelatis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anakuklwsimo_PELPRO> Anakuklwsimo_PELPRO { get; set; }
    }
}
