//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THGL_Managment_System.TESTMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anakuklwsimo_PELPRO
    {
        public string Kwdikos_Anakuklwsis { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Posotita { get; set; }
    
        public virtual Anakuklwnei Anakuklwnei { get; set; }
        public virtual Proion Proion { get; set; }
    }
}
