//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THGL_Managment_System.TESTMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anakuklwse
    {
        public int ID { get; set; }
        public string Kwd_Pelati { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Posotita { get; set; }
        public Nullable<System.DateTime> Hmeromhnia { get; set; }
    
        public virtual Pelatis Pelatis { get; set; }
        public virtual Proion Proion { get; set; }
    }
}
