//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THGL_Managment_System.TESTMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelatis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pelatis()
        {
            this.Anakuklwnei = new HashSet<Anakuklwnei>();
        }
    
        public string Kwdikos_Pelati { get; set; }
        public string Onoma { get; set; }
        public string Epitheto { get; set; }
        public System.DateTime Hm_gennisis { get; set; }
        public string Poli { get; set; }
        public string Tk { get; set; }
        public string Dieuthinsi { get; set; }
        public string Thlefwno { get; set; }
        public string Sxolia { get; set; }
        public Nullable<int> Pontoi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anakuklwnei> Anakuklwnei { get; set; }
    }
}
