//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THGL_Managment_System.TESTMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proion()
        {
            this.Anakuklwsimo_PELPRO = new HashSet<Anakuklwsimo_PELPRO>();
        }
    
        public string Barcode { get; set; }
        public string Onoma { get; set; }
        public string Kathgoria { get; set; }
        public Nullable<int> Pontoi { get; set; }
        public string Anakuklwsimo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anakuklwsimo_PELPRO> Anakuklwsimo_PELPRO { get; set; }
    }
}
