//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THGL_Managment_System.TESTMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class THGLdbEntities : DbContext
    {
        public THGLdbEntities()
            : base("name=THGLdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anakuklwse> Anakuklwse { get; set; }
        public virtual DbSet<Pelatis> Pelatis { get; set; }
        public virtual DbSet<Proion> Proion { get; set; }
    }
}
